List<String> getOracion() {
  return [
    ' ',
    ' ',
    ' ',
    ' ',
    ' Meditación sobre la Oración',
    ' ',
    'La oración es fundamental para la vida espiritual, es el oxígeno del alma. Si al cuerpo le falta oxígeno, se debilita y se fatiga hasta que muere. Así pasa con el alma que no reza, se debilita, se fatiga y ya exhausta muere.',
    ' ',
    'En la oración respiramos a Dios, la presencia de Dios entra en nuestra alma. Su poder llena nuestro ser y despierta en nosotros la voluntad de ser buenos, de ser santos, de ser como Jesús. En la oración, Dios despierta dentro de nosotros la voluntad para alejarnos de las tentaciones, para resistir al demonio, para librarnos de todo el mal. El demonio se da cuenta del poder de la oración, por eso la odia, hace todo lo que puede para impedirnos rezar. Y si, venciendo los esfuerzos del demonio, de todas maneras vamos a rezar, él nos sigue. Siempre está allá para distraernos e interrumpirnos, tratando de hacernos rezar de manera indigna y tibia.',
    ' ',
    'En el Evangelio, Jesús se fue al desierto para rezar, e inmediatamente el diablo aparece para distraer y tentar a Jesús. La oración es el primero y el más grande de todos los Mandamientos. “Amarás al Señor tu Dios con toda tu mente, todo tu corazón, toda tu voluntad y toda tu fuerza,” dice Jesús.',
    ' ',
    'La oración, es lo más necesario en nuestra vida y es la mejor parte. “No muchas cosas son necesarias, sino sólo una. María ha escogido la mejor parte y no le será quitada,” dice Jesús en el Evangelio. ¿Por qué Jesús nos manda que recemos? Es para nosotros, para nuestro bien, para nuestro beneficio.',
    ' ',
    'Dios no necesita nuestra oración. Nuestra oración no aumenta la infinita alegría, felicidad y gloria de Dios. Dios es amor, el amor es dar. El desea darnos más de lo que deseamos recibir. Dios es humilde y no derramará sus dones y bendiciones sobre nosotros por la fuerza, debemos pedirlos.',
    ' ',
    '“Pidan y recibirán. Busquen y encontrarán.” En la oración pedimos, buscamos, y Dios nos responde alegremente con sus gracias y bendiciones. Por la oración, nuestras vidas adquieren una nueva dimensión. Nos convertimos en nuevas criaturas, dejamos la tierra y descubrimos el mundo de Dios, nos transformamos en ángeles. Nuestra mente se expande, nuestros corazones se agrandan. Probamos la dulzura de Dios.',
    ' ',
    'Después de la resurrección, en la Ascensión, Jesús deja la tierra, majestuosamente se eleva a los Cielos y desaparece en las nubes. Esto es lo que pasa cuando rezamos: dejamos esta tierra, ligera y fácilmente nos elevamos y nos perdemos en Dios. Hemos sido creados y destinados para Dios, y sólo si estamos en Dios alcanzaremos la plenitud de que somos capaces, de otra manera, nuestra vida es muy carente e incompleta.',
    ' ',
    'Déjenme darles un ejemplo: como el pato y el águila, ambos son pájaros, pero el pato es pesado y está siempre sobre la tierra. Raramente se eleva a los cielos aletea sobre la cima de las montañas elevándose en una hermosa manera. ¿Que prefieren: ser un pato o un águila?',
    ' ',
    'Recuerden esto, hijitos míos: ustedes no han sido creados para ser gordos patitos que caminan pesadamente sobre la tierra, sino para ser grandes águilas destinadas a elevarse a las alturas para explorar el mundo de Dios. Y harán esto rezando.',
    ' ',
    '¿Cómo debemos rezar? ¿Cuánto tiempo debemos rezar? Las madres Carmelitas rezan seis horas al día. Las Hermanas de María rezan tres horas diariamente.',
    ' ',
    '¿Cuánto debemos rezar? ¿Qué es lo que dice Jesús? Recen siempre y nunca se cansen.” Estén alertas y recen constantemente.” Jesús no nos dice que recemos ocho o seis horas, sino constantemente. “El Padre y Yo somos uno” Él estaba siempre absorto en oración.',
    ' ',
    'En otro lugar del Evangelio está escrito: “Como El siempre acostumbraba hacer.” Jesús estaba siempre rezando.',
    ' ',
    'La pregunta se presenta: ¿Cómo es posible rezar siempre? Tenemos que estudiar, trabajar, jugar, comer, dormir.',
    ' ',
    'Tenemos que distinguir dos tipos de oración: oración formal e informal, oración de alta y baja intensidad. Esta oración formal de alta intensidad requiere concentración, esfuerzo: esta es la meditación, adoración de la Eucaristía, lectura espiritual, Santo Rosario, Vía Crucis. Es obvio que no podemos ofrecer esta oración constantemente, no tenemos tiempo y esto requiere mucho esfuerzo y concentración.',
    ' ',
    'El otro tipo de oración es informal, de baja intensidad: esta requiere poco esfuerzo, es ligera, fácil y refrescante; es sencillamente mirar a Jesús con amor, decir su nombre con amor, pensar en El, recordando Sus palabras, sintiendo su presencia con amor. Este tipo de oración puede ser para todos nosotros. Podemos practicarlo constantemente.',
    ' ',
    'San Juan de la Cruz expresa este tipo de oración, cuando dice: “Estoy siempre consciente de una amorosa presencia en mi vida.” Quien tiene este hábito de oración constante, está siempre lleno de esta presencia de Jesús.',
    ' ',
    'Déjeme darles este ejemplo: una jovencita se enamora de un joven. Constantemente todo el día, sin ningún esfuerzo, piensa en él. La gente la ve y dice: “Está enamorada” Nosotros amamos mucho a Jesús. Por eso, de manera natural, el pensamiento de Dios brota en nuestros corazones. Nos agrada pensar en El. Decimos su nombre. Recordamos sus palabras. Esto nos da un brillo espiritual radiante que cambia y transforma nuestras vidas.',
    ' ',
    'Santa Teresita dice que nunca estuvo más de tres minutos sin que el pensamiento de Dios brotara en su corazón, constantemente pensó en Dios. Esto es lo que deberíamos tratar de hacer…” Jesús mío, Te amo; Dios mío, creo en Ti, María ayúdame”, será una segunda naturaleza en nosotros. Esto es lo que significa rezar siempre, rezar constantemente.',
    ' ',
    'Es importante que nuestra oración esté orientada a la acción, que sea dinámica. Rezamos para hacer lo que agrada a Jesús. No debe ser como la de los paganos, que repiten palabras vacías; no practican lo que predican. Jesús dice: “Si me aman, cumplan mis Mandamientos.”',
    ' ',
    'En la oración, ofrecemos dos moneditas como la viuda pobre en el templo. Eso era todo lo que tenía, ya no podía dar más. Como ella, realmente queremos rezar, tenemos la voluntad de rezar y hacemos nuestro mejor esfuerzo, esa es una oración perfecta y santa.',
    ' ',
    'En conclusión: creamos en la oración, seamos hombres de oración, desarrollemos un hábito de oración. Ofrezcamos la oración de alta intensidad, si tenemos tiempo: meditación adoración, Vía-Crucis, Rosario, lectura espiritual.',
    ' ',
    'Pero constantemente y fácilmente, ofrezcamos esta oración de baja intensidad: mirando a Jesús con amor, diciendo su nombre con fe, pensando en El con devoción.',
    ' ',
    'Nuestra oración debe estar orientada a la acción, debe ser dinámica. Para ofrecer una oración perfecta, sólo se requiere buena voluntad y esfuerzo. Por eso, pensemos acerca de esto. Renovemos nuestro propósito de rezar como rezó Jesús, siempre constantemente.'
        ' ',
    ' ',
  ];
}
